# Generated by Django 4.2.13 on 2024-08-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='player1_disconnected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player1_reconnected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player2_disconnected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player2_reconnected',
            field=models.BooleanField(default=False),
        ),
    ]
