# Generated by Django 4.2.13 on 2024-06-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatars/'),
            preserve_default=False,
        ),
    ]
