# Generated by Django 5.0.6 on 2024-06-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_avatar'),
    ]

    operations = [
    ]
