# Generated by Django 5.0.6 on 2024-06-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20240613_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/Users/macuser/Desktop/ft_transcendence/backend/media/player/None/user_avatar/avatar1.png', upload_to='avatars/'),
            preserve_default=False,
        ),
    ]
