# Generated by Django 4.2.13 on 2024-09-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ImgPath',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='msgType',
            field=models.CharField(choices=[('text', 'Text message'), ('image', 'Image message')], default='text', max_length=5),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
