# Generated by Django 4.2.13 on 2024-07-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content_type',
            field=models.CharField(choices=[('T', 'TEXT'), ('IMG', 'IMAGE')], max_length=3),
        ),
    ]
