# Generated by Django 4.2.13 on 2024-07-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
