# Generated by Django 4.2.13 on 2024-09-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ImgPath',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='chat_images/'),
        ),
    ]
