# Generated by Django 4.2.13 on 2024-06-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('avatar', models.CharField(max_length=255)),
                ('rank', models.CharField(default='B', max_length=1)),
                ('rank_progress', models.DecimalField(decimal_places=2, max_digits=5)),
                ('games_played', models.IntegerField()),
                ('games_won', models.IntegerField()),
                ('xp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
