# Generated by Django 4.2.13 on 2024-06-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_player_created_at_remove_player_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('achievementImg', models.URLField()),
                ('achievementTask', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank_progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
