# Generated by Django 4.2.13 on 2024-06-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_globalachievements_alter_player_avatar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalAchievements',
        ),
    ]
