# Generated by Django 4.2.13 on 2024-06-08 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0004_delete_globalachievements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('notification_link', models.URLField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('to_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_status', models.CharField(choices=[('A', 'ACCEPTED'), ('P', 'PENDING'), ('D', 'DECLINED')], default='P', max_length=10)),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('player_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_invitations', to=settings.AUTH_USER_MODEL)),
                ('player_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('player_sender', 'player_receiver')},
            },
        ),
    ]
