# Generated by Django 4.2.13 on 2024-06-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_player_avatar'),
        ('user_management', '0007_remove_player_id_alter_player_user'),
    ]

    operations = [
    ]
