# Generated by Django 4.2.13 on 2024-09-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_alter_localtournamanetparticipants_loosers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localtournamentuser',
            name='keys',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localtournamentuser',
            name='paddle_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
