# Generated by Django 4.2.13 on 2024-06-08 11:01

from django.db import migrations, models
import user_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_player_id_alter_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(default=1, upload_to=[user_management.models.user_avatar_upload_path]),
            preserve_default=False,
        ),
    ]
