# Generated by Django 4.2.13 on 2024-09-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_alter_localtournamanetparticipants_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localtournament',
            name='tournament_participants',
            field=models.ManyToManyField(related_name='tournaments', to='user_management.localplayer'),
        ),
    ]
