# Generated by Django 4.2.13 on 2024-09-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0013_localtournament_tournament_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localtournament',
            name='tournament_participants',
        ),
    ]
