# Generated by Django 4.2.13 on 2024-06-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0013_remove_player_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='avatar',
        ),
    ]
