# Generated by Django 4.2.13 on 2024-09-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0016_localtournament_is_online_tournament_is_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localtournament',
            name='tournament_participants',
            field=models.ManyToManyField(related_name='local_tournament_participants', to='user_management.localplayer'),
        ),
    ]
