# Generated by Django 4.2.13 on 2024-09-25 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0017_localtournament_tournament_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localtournament',
            name='tournament_participants',
        ),
        migrations.AddField(
            model_name='localplayer',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='user_management.localtournament'),
        ),
    ]
