# Generated by Django 5.0.7 on 2024-07-24 19:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0021_alter_friendship_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendship',
            name='unique_friendship',
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('player', 'friend')},
        ),
    ]
