# Generated by Django 4.2.13 on 2024-07-25 09:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0021_alter_friendship_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendship',
            name='unique_friendship',
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('player', 'friend')},
        ),
    ]
