# Generated by Django 4.2.13 on 2024-08-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0022_remove_friendship_unique_friendship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
