# Generated by Django 4.2.13 on 2024-08-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0023_notification_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
