# Generated by Django 4.2.13 on 2024-08-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0025_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.CharField(default='BRONZE', max_length=1),
        ),
    ]
