# Generated by Django 4.2.13 on 2024-08-13 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0027_tournament_tournamentparticipants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_prize',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_status',
            field=models.BooleanField(default=False),
        ),
    ]
