# Generated by Django 4.2.13 on 2024-08-13 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0028_tournament_tournament_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_participants',
            field=models.ManyToManyField(related_name='tournament_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
