# Generated by Django 4.2.13 on 2024-08-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0030_tournamentparticipants_player1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_stage',
            field=models.CharField(default='semi-finals', max_length=100),
        ),
    ]
