# Generated by Django 4.2.13 on 2024-08-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0032_tournamentparticipants_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipants',
            name='matchPlayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentparticipants',
            name='matchStage',
            field=models.CharField(default='semi-finals', max_length=100),
        ),
    ]
