# Generated by Django 5.0.6 on 2024-06-11 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_score', models.IntegerField()),
                ('loser_score', models.IntegerField()),
                ('game_type', models.CharField(choices=[('casual', 'Casual'), ('ranked', 'Ranked')], max_length=20)),
                ('match_type', models.CharField(choices=[('single', 'Single Match'), ('tournament', 'Tournament Match')], max_length=20)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('loser_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_games', to=settings.AUTH_USER_MODEL)),
                ('winner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
