# Generated by Django 4.2.13 on 2024-06-12 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0013_remove_player_friends'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='game_type',
            field=models.CharField(choices=[('pingpong', 'Ping Pong'), ('xo', 'XO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='loser_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_games', to='user_management.player'),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='winner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to='user_management.player'),
        ),
    ]
