# Generated by Django 4.2.13 on 2024-08-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamechallenge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamechallenge',
            old_name='invite_status',
            new_name='status',
        ),
    ]
