# Generated by Django 5.0.6 on 2024-06-13 10:06

import django.db.models.deletion
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gamehistory_game_type_and_more'),
        ('user_management', '0013_remove_player_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=game.models.achievment_image_upload_path)),
                ('task', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.player')),
            ],
        ),
    ]
