# Generated by Django 4.2.13 on 2024-08-15 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0034_alter_tournamentparticipants_matchstage'),
        ('game', '0003_rename_invite_status_gamechallenge_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteGameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_waiting', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited1', to='user_management.player')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited2', to='user_management.player')),
            ],
        ),
    ]
