# Generated by Django 5.0.4 on 2024-07-05 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_achievement_playerachievement'),
        ('user_management', '0014_remove_player_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(max_length=255)),
                ('paddle', models.CharField(max_length=7)),
                ('gameMode', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.player')),
            ],
        ),
    ]
