# Generated by Django 4.2.13 on 2024-09-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_localplayer_localgameroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='localgameroom',
            name='arena',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localplayer',
            name='keys',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localplayer',
            name='paddle_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='localplayer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
