# Generated by Django 4.2.13 on 2024-08-15 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_invitegameroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamechallenge',
            name='invite_game_room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.invitegameroom'),
        ),
    ]
