# Generated by Django 4.2.13 on 2024-07-08 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_gamesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='loser_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='winner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
