# Generated by Django 4.2.13 on 2024-10-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_localgameroom_player1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesettings',
            name='background',
            field=models.CharField(default='hell', max_length=255),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='keys',
            field=models.CharField(default='up-down', max_length=255),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='paddle',
            field=models.CharField(default='#BC4F00', max_length=255),
        ),
    ]
