# Generated by Django 4.2.13 on 2024-08-19 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0034_alter_tournamentparticipants_matchstage'),
        ('game', '0006_invitegameroom_player1_connected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentGameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_waiting', models.BooleanField(default=True)),
                ('crateated_at', models.DateTimeField(auto_now_add=True)),
                ('player1_connected', models.BooleanField(default=False)),
                ('player2_connected', models.BooleanField(default=False)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_player1', to='user_management.player')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_player2', to='user_management.player')),
            ],
        ),
    ]
