# Generated by Django 4.2.13 on 2024-07-08 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0018_remove_player_id_alter_player_user'),
        ('game', '0006_alter_gamesettings_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='loser_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_games', to='user_management.player'),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='winner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to='user_management.player'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.player'),
        ),
        migrations.AlterField(
            model_name='playerachievement',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.player'),
        ),
    ]
