# Generated by Django 4.2.13 on 2024-07-08 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0018_remove_player_id_alter_player_user'),
        ('game', '0007_alter_gamehistory_loser_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesettings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.player'),
        ),
    ]
