# Generated by Django 4.2.13 on 2024-07-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_gamesettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesettings',
            name='gameMode',
            field=models.CharField(default='flesh', max_length=255),
        ),
    ]
