# Generated by Django 4.2.13 on 2024-07-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_gamesettings_gamemode'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='keys',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
