# Generated by Django 4.2.13 on 2024-09-14 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0003_xphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipants',
            name='loosers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loosers', to=settings.AUTH_USER_MODEL),
        ),
    ]
