# Generated by Django 4.2.13 on 2024-09-23 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_management.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0004_tournamentparticipants_loosers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=100)),
                ('tournament_map', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament_status', models.BooleanField(default=False)),
                ('tournament_stage', models.CharField(default='semi-finals', max_length=100)),
                ('tournament_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocalTournamentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to=user_management.models.user_avatar_upload_path)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.localtournament')),
            ],
        ),
        migrations.AddField(
            model_name='localtournament',
            name='tournament_participants',
            field=models.ManyToManyField(related_name='tournament_participants', to='user_management.localtournamentuser'),
        ),
    ]
