# Generated by Django 4.2.13 on 2024-09-23 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_localtournament_localtournamentuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localtournament',
            name='tournament_participants',
        ),
        migrations.AlterField(
            model_name='localtournamentuser',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='user_management.localtournament'),
        ),
    ]
