# Generated by Django 4.2.13 on 2024-09-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_localtournamentuser_keys_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('paddle_color', models.CharField(blank=True, max_length=7, null=True)),
                ('keys', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='localtournamentuser',
            name='keys',
        ),
        migrations.RemoveField(
            model_name='localtournamentuser',
            name='paddle_color',
        ),
    ]
