# Generated by Django 4.2.13 on 2024-09-24 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_localplayer_remove_localtournamentuser_keys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localtournamanetparticipants',
            name='loosers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_loosers', to='user_management.localplayer'),
        ),
        migrations.AlterField(
            model_name='localtournamanetparticipants',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_player1', to='user_management.localplayer'),
        ),
        migrations.AlterField(
            model_name='localtournamanetparticipants',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_player2', to='user_management.localplayer'),
        ),
        migrations.AlterField(
            model_name='localtournamanetparticipants',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.localplayer'),
        ),
        migrations.AlterField(
            model_name='localtournamanetparticipants',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_winner', to='user_management.localplayer'),
        ),
    ]
