# Generated by Django 4.2.13 on 2024-09-24 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_alter_localtournamanetparticipants_loosers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localtournamanetparticipants',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.localtournament'),
        ),
        migrations.DeleteModel(
            name='LocalTournamentUser',
        ),
    ]
