# Generated by Django 4.2.13 on 2024-09-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0015_alter_localplayer_paddle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='localtournament',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='localplayer',
            name='paddle_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
