# Generated by Django 4.2.13 on 2024-10-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0018_remove_localtournament_tournament_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localtournament',
            name='tournament_stage',
            field=models.CharField(default='SEMI-FINALS', max_length=100),
        ),
    ]
