# Generated by Django 4.2.13 on 2024-12-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0020_tournament_all_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_stage',
            field=models.CharField(default='SEMI-FINALS', max_length=100),
        ),
    ]
